coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_not_found: success
        if_ci_failed: error
        informational: false
    patch:
      default:
        target: 70%
        threshold: 5%
        if_not_found: success
        if_ci_failed: error
        informational: false

  ignore:
    - "**/*_test.go"
    - "**/testdata/**"
    - "**/vendor/**"
    - "**/examples/**"
    - "**/*.pb.go"
    - "**/*.generated.go"
    - "**/main.go"
    - "**/hack/**"

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

github_checks:
  annotations: true
